Proj 38 ace ports on cva6
planvtech/culsans pull request #5
Opened 2022-10-17 21:25 UTC by suppamax

2022-10-20 17:13 UTC, BasitSajjad commented on rtl/include/culsans_pkg.sv
> +      ace_pkg::arsnoop_t snoop;
it is better to use arsnoop instead of snoop as assign.svh expects it as arsnoop

2022-10-20 17:13 UTC, BasitSajjad commented on rtl/include/culsans_pkg.sv
> +      ace_pkg::awsnoop_t snoop;
awsnoop instead of snoop

2022-10-20 17:23 UTC, BasitSajjad commented on rtl/src/culsans_top.sv
> -  axi_xbar_intf #(
Snoop interface is missing. Please add from recent PR24

2022-10-20 17:34 UTC, BasitSajjad requested changes
In general it looks good.  Few suggestions are mentioned in comments. Please see them.

2022-10-20 17:55 UTC, suppamax commented on rtl/include/culsans_pkg.sv
> +      ace_pkg::arsnoop_t snoop;
I find aw_awsoop redundant.
In a later commit I have modified the naming in axi accordingly

2022-10-20 17:55 UTC, suppamax commented on rtl/include/culsans_pkg.sv
> +      ace_pkg::awsnoop_t snoop;
See above

2022-10-21 07:26 UTC, suppamax commented on rtl/src/culsans_top.sv
> -  axi_xbar_intf #(
I propose to integrate this in the next iteration (i.e. PROJ19 and PROJ20).

Nesting PRs might make things unnecessarily complicated

2022-11-02 17:28 UTC, BasitSajjad approved these changes

2022-11-03 06:53 UTC, merged